gsutil cp gs://nindate/wip_ninstack_mitaka/0-juno-multinode-amqp-1-install.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/0-juno-multinode-ctrl-0-prepare.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/0-juno-multinode-db-0-prepare.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/0-juno-multinode-db-1-install.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/0-juno-multinode-db-2-create-databases.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/0-juno-multinode-memcached-1-install.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/1-juno-multinode-ctrl-1-keystone.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/1-juno-multinode-ctrl-2-keystone-db-manage.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/1-juno-multinode-ctrl-3-keystone-create-users-tenants-roles.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/12-juno-multinode-comp-1-nova.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/13-juno-multinode-comp-2-neutron.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/2-juno-multinode-ctrl-1-glance.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/2-juno-multinode-ctrl-2-glance-db-manage.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/3-juno-multinode-ctrl-1-nova.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/3-juno-multinode-ctrl-2-nova-db-manage.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/4-juno-multinode-ctrl-1-neutron.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/4-juno-multinode-ctrl-2-neutron-db-manage.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/5-juno-multinode-ctrl-5-horizon.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/6-juno-multinode-ctrl-6-cinder.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/6-juno-multinode-stor-6-cinder.sh .
gsutil cp gs://nindate/wip_ninstack_mitaka/config.cfg .
gsutil cp gs://nindate/wip_ninstack_mitaka/wrapper.sh .
chmod u+x *.sh
